version: '3'
services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-tree-app
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
